In [1]:
import numpy as np
print(np.__version__)

1.19.4


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [5]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [9]:
list = [1,2,3,4,5,6,7]
result = np.array(list)
result

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.full((2,2),True,dtype = bool)

array([[ True,  True],
       [ True,  True]])

In [13]:
np.random.randint(0,10,(3,3))

array([[9, 6, 0],
       [4, 8, 5],
       [3, 4, 6]])

In [14]:
np.random.randn(3,3)

array([[ 0.03341025,  0.60174845,  0.37364002],
       [ 1.34209995, -0.43689171,  0.4319744 ],
       [-0.31305773,  0.34345325,  0.84052602]])

In [15]:
result.nbytes

28

In [16]:
result

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
result = result.astype(float)
result

array([1., 2., 3., 4., 5., 6., 7.])

In [18]:
result[result %2 ==0]

array([2., 4., 6.])

In [19]:
re = np.diag([5,4,8,9])

In [20]:
re

array([[5, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [21]:
a = re[:,[2,1,3,0]]
a

array([[0, 0, 0, 5],
       [0, 4, 0, 0],
       [8, 0, 0, 0],
       [0, 0, 9, 0]])

In [22]:
a == re

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True, False, False]])

In [23]:
len(np.argwhere(a == re))

10

In [24]:
(a == re).sum()

10

In [25]:
np.argwhere(a == re)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 3],
       [3, 0],
       [3, 1]], dtype=int64)

In [26]:
np.dot(a,re)   #矩阵乘法

array([[ 0,  0,  0, 45],
       [ 0, 16,  0,  0],
       [40,  0,  0,  0],
       [ 0,  0, 72,  0]])

In [27]:
a*re    #对应元素相乘

array([[ 0,  0,  0,  0],
       [ 0, 16,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [28]:
np.linalg.det(a)

1439.999999999999

In [29]:
np.linalg.inv(a)

array([[0.        , 0.        , 0.125     , 0.        ],
       [0.        , 0.25      , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.11111111],
       [0.2       , 0.        , 0.        , 0.        ]])

In [31]:
a = np.matrix(a)
a

matrix([[0, 0, 0, 5],
        [0, 4, 0, 0],
        [8, 0, 0, 0],
        [0, 0, 9, 0]])

In [32]:
b = np.matrix(re)
b

matrix([[5, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 8, 0],
        [0, 0, 0, 9]])

In [34]:
np.hstack((a,b))

matrix([[0, 0, 0, 5, 5, 0, 0, 0],
        [0, 4, 0, 0, 0, 4, 0, 0],
        [8, 0, 0, 0, 0, 0, 8, 0],
        [0, 0, 9, 0, 0, 0, 0, 9]])

In [35]:
np.vstack((a,b))

matrix([[0, 0, 0, 5],
        [0, 4, 0, 0],
        [8, 0, 0, 0],
        [0, 0, 9, 0],
        [5, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 8, 0],
        [0, 0, 0, 9]])

In [37]:
new = np.pad(a,pad_width = 1 ,constant_values = 1)    ###外围填充数字

In [38]:
new

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 5, 1],
       [1, 0, 4, 0, 0, 1],
       [1, 8, 0, 0, 0, 1],
       [1, 0, 0, 9, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [39]:
a

matrix([[0, 0, 0, 5],
        [0, 4, 0, 0],
        [8, 0, 0, 0],
        [0, 0, 9, 0]])

In [40]:
news = np.pad(a,pad_width = 3 ,constant_values = 5)
news

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 0, 0, 0, 5, 5, 5, 5],
       [5, 5, 5, 0, 4, 0, 0, 5, 5, 5],
       [5, 5, 5, 8, 0, 0, 0, 5, 5, 5],
       [5, 5, 5, 0, 0, 9, 0, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [41]:
np.argwhere(news>5)

array([[5, 3],
       [6, 5]], dtype=int64)

In [42]:
np.sum(news,0)  #案列求和

array([50, 50, 50, 38, 34, 39, 35, 50, 50, 50])

In [43]:
np.sum(news,1)

array([50, 50, 50, 35, 34, 38, 39, 50, 50, 50])

In [44]:
data = np.random.randint(1,100,(6,6))
data

array([[61, 57, 59, 76, 87, 30],
       [43, 85, 57, 35, 47,  7],
       [78, 75, 73,  9, 68, 68],
       [77, 40, 47, 22, 50, 80],
       [50, 22,  5, 15, 79, 64],
       [84, 28,  7,  2, 14, 15]])

In [45]:
np.argmax(data,axis = 0)

array([5, 1, 2, 0, 0, 3], dtype=int64)

In [46]:
np.unique(data,return_counts = True)

(array([ 2,  5,  7,  9, 14, 15, 22, 28, 30, 35, 40, 43, 47, 50, 57, 59, 61,
        64, 68, 73, 75, 76, 77, 78, 79, 80, 84, 85, 87]),
 array([1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [47]:
data.argsort()

array([[5, 1, 2, 0, 3, 4],
       [5, 3, 0, 4, 2, 1],
       [3, 4, 5, 2, 1, 0],
       [3, 1, 2, 4, 0, 5],
       [2, 3, 1, 0, 5, 4],
       [3, 2, 4, 5, 1, 0]], dtype=int64)

In [48]:
np.repeat(data,2,axis = 0)

array([[61, 57, 59, 76, 87, 30],
       [61, 57, 59, 76, 87, 30],
       [43, 85, 57, 35, 47,  7],
       [43, 85, 57, 35, 47,  7],
       [78, 75, 73,  9, 68, 68],
       [78, 75, 73,  9, 68, 68],
       [77, 40, 47, 22, 50, 80],
       [77, 40, 47, 22, 50, 80],
       [50, 22,  5, 15, 79, 64],
       [50, 22,  5, 15, 79, 64],
       [84, 28,  7,  2, 14, 15],
       [84, 28,  7,  2, 14, 15]])

In [49]:
np.unique(data,axis=0)

array([[43, 85, 57, 35, 47,  7],
       [50, 22,  5, 15, 79, 64],
       [61, 57, 59, 76, 87, 30],
       [77, 40, 47, 22, 50, 80],
       [78, 75, 73,  9, 68, 68],
       [84, 28,  7,  2, 14, 15]])

In [52]:
data[0]  ###得到第一行的数组

array([61, 57, 59, 76, 87, 30])

In [59]:
data[0:1].shape  ####得到第一行的二维数组

(1, 6)

In [60]:
data[0].shape   ###一维数组

(6,)

In [61]:
data

array([[61, 57, 59, 76, 87, 30],
       [43, 85, 57, 35, 47,  7],
       [78, 75, 73,  9, 68, 68],
       [77, 40, 47, 22, 50, 80],
       [50, 22,  5, 15, 79, 64],
       [84, 28,  7,  2, 14, 15]])

In [62]:
a = data[1:2]
b = data[2:3]
index = np.isin(a,b)
array = a[~index]
print(index)
print(array)

[[False False False False False False]]
[43 85 57 35 47  7]


In [65]:
data1 = data.astype(float)
data1[data1<50] =np.nan
data1

array([[61., 57., 59., 76., 87., nan],
       [nan, 85., 57., nan, nan, nan],
       [78., 75., 73., nan, 68., 68.],
       [77., nan, nan, nan, 50., 80.],
       [50., nan, nan, nan, 79., 64.],
       [84., nan, nan, nan, nan, nan]])

In [66]:
data

array([[61, 57, 59, 76, 87, 30],
       [43, 85, 57, 35, 47,  7],
       [78, 75, 73,  9, 68, 68],
       [77, 40, 47, 22, 50, 80],
       [50, 22,  5, 15, 79, 64],
       [84, 28,  7,  2, 14, 15]])

In [67]:
vals,counts = np.unique(data[0:2] ,return_counts = True)
print(vals,counts)

[ 7 30 35 43 47 57 59 61 76 85 87] [1 1 1 1 1 2 1 1 1 1 1]


In [68]:
x = 100
data.flat[np.abs(data-x).argmin()]

87

In [69]:
data - data.mean()

array([[ 13.33333333,   9.33333333,  11.33333333,  28.33333333,
         39.33333333, -17.66666667],
       [ -4.66666667,  37.33333333,   9.33333333, -12.66666667,
         -0.66666667, -40.66666667],
       [ 30.33333333,  27.33333333,  25.33333333, -38.66666667,
         20.33333333,  20.33333333],
       [ 29.33333333,  -7.66666667,  -0.66666667, -25.66666667,
          2.33333333,  32.33333333],
       [  2.33333333, -25.66666667, -42.66666667, -32.66666667,
         31.33333333,  16.33333333],
       [ 36.33333333, -19.66666667, -40.66666667, -45.66666667,
        -33.66666667, -32.66666667]])

In [72]:
arr1 = np.random.randint(1,6,6)
arr1

array([2, 3, 5, 2, 5, 4])

In [5]:
import pandas as pd


In [3]:
from sklearn import tree