In [5]:
import torch

In [6]:
print(torch)

<module 'torch' from 'E:\\environment\\lib\\site-packages\\torch\\__init__.py'>


In [7]:
import torch
x = torch.rand(5,5)
print(x)

tensor([[3.1443e-01, 8.8916e-01, 7.5295e-01, 2.1316e-01, 2.3660e-01],
        [6.4373e-06, 7.4239e-01, 9.6569e-01, 6.7101e-01, 6.0302e-01],
        [6.6825e-01, 3.0334e-01, 6.5621e-01, 1.7789e-02, 1.7677e-01],
        [5.7383e-01, 2.5398e-01, 4.2228e-01, 4.2351e-02, 2.3473e-01],
        [2.8639e-01, 6.7583e-01, 8.1753e-02, 3.9315e-01, 7.2190e-02]])


In [8]:
from __future__ import print_function
import torch
x = torch.empty(5,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.7208e-42, 0.0000e+00],
        [0.0000e+00, 7.5338e+28, 0.0000e+00]])

In [9]:
x = torch.zeros(5,3,dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [11]:
x = x.new_ones(5,3,dtype = torch.long)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [12]:
y = torch.ones(5,3,dtype = torch.long)
y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [13]:
x ==y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [14]:
x == y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [15]:
x = torch.randn_like(x,dtype = torch.float)
x

tensor([[-0.2977,  0.8550,  0.5664],
        [-0.4756,  1.0376,  2.0850],
        [ 0.5640, -0.4001, -0.2572],
        [-1.0277, -1.4311,  0.3186],
        [ 1.1948,  1.3782,  0.0441]])

In [16]:
x.size()

torch.Size([5, 3])

In [17]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x

tensor([[0.2422, 0.5204, 0.7452, 0.8876],
        [0.7353, 0.5044, 0.6572, 0.7965],
        [0.4599, 0.3229, 0.1214, 0.6902],
        [0.2238, 0.7648, 0.0862, 0.9281]])

In [19]:
y

tensor([0.2422, 0.5204, 0.7452, 0.8876, 0.7353, 0.5044, 0.6572, 0.7965, 0.4599,
        0.3229, 0.1214, 0.6902, 0.2238, 0.7648, 0.0862, 0.9281])

In [20]:
z

tensor([[0.2422, 0.5204, 0.7452, 0.8876, 0.7353, 0.5044, 0.6572, 0.7965],
        [0.4599, 0.3229, 0.1214, 0.6902, 0.2238, 0.7648, 0.0862, 0.9281]])

In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.4300])
-1.4299802780151367


In [22]:
x = torch.ones(2,2,requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [23]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [25]:
print(y.grad_fn)

In [26]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [29]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [30]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [32]:
print(x.grad)

None


In [34]:
print(a.grad)

None


In [35]:
a

tensor([[-1.3871e-03,  1.3247e+00],
        [ 1.9034e+00,  1.4961e+01]], requires_grad=True)

In [37]:
print(b.grad)

None


In [38]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [39]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [49]:
y.data  #只提取数据

tensor([[3., 3.],
        [3., 3.]])

In [51]:
y.data.norm()  #对y中的所有数据进行平方后求和在取平方根，相当于求L2范数

tensor(6.)

In [57]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    def forward(self,x):     #x表示传进来的图片灰度图
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(-1,self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *=s
        return num_features        

In [58]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [59]:
x.size()

torch.Size([2, 2])

In [60]:
x.size()[1:]

torch.Size([2])

In [61]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


In [64]:
for i in params:
    print(i.size())

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([16, 6, 5, 5])
torch.Size([16])
torch.Size([120, 400])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [65]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0590, -0.1353, -0.0044, -0.1189, -0.0857, -0.0050, -0.0293,  0.1007,
         -0.0471, -0.0007]], grad_fn=<AddmmBackward>)


In [66]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [68]:
output = net(input)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()
loss = criterion(output,target)
print(loss)

tensor(0.7953, grad_fn=<MseLossBackward>)


In [72]:
loss.grad_fn

In [73]:
input

tensor([[[[ 0.2354, -0.0766,  1.1295,  ..., -1.4294, -0.7371, -0.0778],
          [-0.5849,  0.2805, -0.6392,  ...,  0.9815, -1.3367, -0.9790],
          [-0.9583,  0.8903, -1.6259,  ...,  1.0736, -0.0655,  1.3185],
          ...,
          [ 0.7928, -1.1754, -0.7223,  ...,  1.3326,  1.0650, -0.5668],
          [-0.2290,  0.6045,  0.7039,  ..., -0.5431,  0.8750,  0.4415],
          [-0.1680,  0.8796,  0.8897,  ..., -0.5733,  0.7152, -0.0341]]]])

In [74]:
net.zero_grad()
print(net.conv1.bias.grad)
loss.backward()
print(net.conv1.bias.grad)

tensor([0., 0., 0., 0., 0., 0.])
tensor([-0.0139, -0.0149, -0.0070, -0.0015, -0.0116,  0.0021])


In [75]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(),lr = 0.01)
optimizer.zero_grad()
output = net(input)
loss = criterion(output,target)
loss.backward()
optimizer.step()