In [10]:
import torch

In [11]:
a = torch.randn(2,3)
a

tensor([[-1.5072,  0.3664, -0.8760],
        [-0.5761, -0.9658, -0.2166]])

In [12]:
a.type()

'torch.FloatTensor'

In [13]:
type(a)

torch.Tensor

In [15]:
isinstance(a,torch.FloatTensor)

True

In [16]:
torch.tensor(1.0)

tensor(1.)

In [17]:
torch.tensor(1.3)

tensor(1.3000)

In [18]:
torch.tensor(1)

tensor(1)

In [19]:
a = torch.tensor(2.2)

In [20]:
a.shape

torch.Size([])

In [21]:
len(a.shape)

0

In [22]:
a.size()

torch.Size([])

In [23]:
b = torch.tensor([1.1])

In [24]:
b

tensor([1.1000])

In [25]:
b.shape

torch.Size([1])

In [26]:
c = torch.tensor([1.2,3.4])
c

tensor([1.2000, 3.4000])

In [27]:
c.shape

torch.Size([2])

In [28]:
d = torch.FloatTensor(1)
d

tensor([-1.0842e-19])

In [29]:
import numpy as np
data = np.ones(5)
data

array([1., 1., 1., 1., 1.])

In [30]:
da = np.ones([5,5])
da

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
torch.from_numpy(data)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [32]:
a = torch.ones(2)
a

tensor([1., 1.])

In [33]:
a.shape

torch.Size([2])

In [34]:
a = torch.randn(2,3)
a

tensor([[ 0.0453, -1.0996,  0.8376],
        [-0.0131, -0.1165,  1.6459]])

In [35]:
a.shape

torch.Size([2, 3])

In [36]:
a.size()

torch.Size([2, 3])

In [37]:
a.dim()

2

In [38]:
a.numel()

6

In [39]:
torch.full([5,5],7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

In [40]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [44]:
a = torch.rand(4,3,28,28)
a

tensor([[[[0.4525, 0.2467, 0.5083,  ..., 0.8623, 0.3804, 0.6429],
          [0.6084, 0.6805, 0.2114,  ..., 0.1541, 0.5542, 0.3428],
          [0.4012, 0.7317, 0.3425,  ..., 0.6011, 0.1512, 0.9991],
          ...,
          [0.6656, 0.8476, 0.2023,  ..., 0.8333, 0.1944, 0.3226],
          [0.7868, 0.5891, 0.9274,  ..., 0.9739, 0.6225, 0.5230],
          [0.0515, 0.5695, 0.5768,  ..., 0.8997, 0.2862, 0.9436]],

         [[0.6373, 0.0307, 0.9876,  ..., 0.6809, 0.6180, 0.4592],
          [0.6871, 0.2521, 0.7132,  ..., 0.8199, 0.1288, 0.9995],
          [0.7809, 0.7566, 0.7094,  ..., 0.9673, 0.5201, 0.6521],
          ...,
          [0.1684, 0.6735, 0.0021,  ..., 0.8857, 0.3616, 0.3197],
          [0.7400, 0.9176, 0.8883,  ..., 0.5388, 0.9577, 0.1946],
          [0.0422, 0.8526, 0.4459,  ..., 0.8811, 0.7172, 0.0312]],

         [[0.2512, 0.4812, 0.8695,  ..., 0.7498, 0.5118, 0.6944],
          [0.2462, 0.4651, 0.9102,  ..., 0.9056, 0.0694, 0.6405],
          [0.6126, 0.2170, 0.6027,  ..., 0

In [45]:
a[0].shape

torch.Size([3, 28, 28])

In [46]:
x = torch.randn(3,4)
x

tensor([[ 0.0430,  0.0196, -0.6611,  2.2706],
        [ 1.6432,  2.2533, -1.0537,  0.9733],
        [-0.6428, -1.1743, -0.8157,  0.1133]])

In [47]:
mask = x.ge(0.5)
mask

tensor([[0, 0, 0, 1],
        [1, 1, 0, 1],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [49]:
torch.masked_select(x,mask)

tensor([2.2706, 1.6432, 2.2533, 0.9733])

In [50]:
y = torch.tensor([[4,3,5],[6,7,8]])
y

tensor([[4, 3, 5],
        [6, 7, 8]])

In [51]:
torch.take(y,torch.tensor([0,2,5]))

tensor([4, 5, 8])

In [52]:
a = torch.tensor([4,3,28,28])
a.shape

torch.Size([4])

In [54]:
b = torch.randn(4,3,28,28)
b.shape

torch.Size([4, 3, 28, 28])

In [58]:
b.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [59]:
torch.arange(28)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [60]:
b.index_select(0,torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [61]:
x = [1,2]
torch.is_tensor(x)

False

In [63]:
torch.numel(b)    # 统计tensor中的元素个数

9408

In [64]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [65]:
x = np.array([3,4,5,6])
x

array([3, 4, 5, 6])

In [66]:
torch.from_numpy(x)

tensor([3, 4, 5, 6], dtype=torch.int32)

In [67]:
torch.rand(10)   # 创建均匀分布【0,1）

tensor([0.4922, 0.6294, 0.8956, 0.5709, 0.8392, 0.6830, 0.2640, 0.2832, 0.0453,
        0.9337])

In [68]:
torch.randn(10)   # 创建均值为0，方差为1的正态分布

tensor([-1.9063e+00, -9.9594e-01, -3.8469e-02,  4.0469e-01,  2.1735e+00,
        -1.5166e+00, -1.3683e+00, -8.4577e-04, -4.5535e-01, -1.2135e+00])

In [69]:
torch.randperm(10)    # 创建10个0到9的打乱的随机整数

tensor([3, 4, 1, 0, 2, 8, 9, 7, 6, 5])

In [70]:
torch.randperm(20)

tensor([ 3,  1, 16,  4,  2, 10, 11, 18, 12, 17, 19,  8,  5, 13, 15, 14,  0,  9,
         6,  7])

In [72]:
x = torch.randint(1,99,(5,5))
x

tensor([[53, 51, 29, 77, 82],
        [69, 89, 86, 88, 30],
        [21, 47, 37, 66, 10],
        [27, 96, 10, 94, 66],
        [ 3, 92, 64, 83, 73]])

In [73]:
torch.argmax(x,dim = 0)

tensor([1, 3, 1, 3, 0])

In [74]:
torch.cat((x,x))   # 合并，默认行合并

tensor([[53, 51, 29, 77, 82],
        [69, 89, 86, 88, 30],
        [21, 47, 37, 66, 10],
        [27, 96, 10, 94, 66],
        [ 3, 92, 64, 83, 73],
        [53, 51, 29, 77, 82],
        [69, 89, 86, 88, 30],
        [21, 47, 37, 66, 10],
        [27, 96, 10, 94, 66],
        [ 3, 92, 64, 83, 73]])

In [75]:
x

tensor([[53, 51, 29, 77, 82],
        [69, 89, 86, 88, 30],
        [21, 47, 37, 66, 10],
        [27, 96, 10, 94, 66],
        [ 3, 92, 64, 83, 73]])

In [76]:
torch.chunk(x,2,0)   # qie

(tensor([[53, 51, 29, 77, 82],
         [69, 89, 86, 88, 30],
         [21, 47, 37, 66, 10]]),
 tensor([[27, 96, 10, 94, 66],
         [ 3, 92, 64, 83, 73]]))

In [1]:
import pandas as pd
data = pd.read_excel(r"C:\Users\Administrator\Desktop\寒假沟通记录表.xlsx")
data

姓名                                               沟通情况  \
0          黄希蕊                     阅读理解、记忆力比同龄人差一点，觉得时间太紧张了 没时间阅读   
1          郭晓涵               课外阅读、课外文言文，学校秋季加了课，秋季部分课程没有上完，说了9天计划   
2           于涵              18.19期末考试结束，语文中上，120不低于95，深圳，基本98-109   
3          陈雪利          等星期天晚上哈，学习方面很多地方还要问娃娃自己，因为娃娃大了好多东西问她她说我不懂   
4          夏铭浩               总分150,21.22期末考试，晚上九点十分放学，发孩子微信 和孩子沟通   
5          宫肇轩                                              微信没人接   
6          于雯淼  秋季后半段没怎么上课，时间比较紧张，学校是周一到周六上课，集中学习，寒假春季的课程如果到时候...   
7          杜婧蕾                                                NaN   
8          郝翊帆  觉得课上作业简单不想做，网课比较多，作业也很多，语文不是特别好，跟之前辅导老师沟通过，最近成...   
9          彭俊怡                                              微信忙线中   
10         王嘉皓             还是在基础不好，没有大的改观。目前是在准备期末考试，学习自觉性上还是可以的。   
11         姜宇婷  谢谢秀珍老师的关心和厚爱，马上期末考试了，能给她推荐点卷子让她做一下吗？比较贪玩，需要给孩子...   
12         宋文浩  下周期末考试，好像下周三考试，初一开始上学而思，换老师比较多，家长比较忙关注度不高，学校里面...   
13          李鹏  最近一次考试成绩下降了，语文中等水平，住校的，妈妈对孩子的学习情况不是很清楚，似乎文言文不太...   
14         李科达                                 住校不在家，科达爸爸，孩子回家了吗？   
15         赵启正                                              微信未接通   
16         陈若文                                             20期末考试   
17         孙雨涵                                          嗯 我只能先保存哦   
18         李其恩  谢谢老师，疫情缘故，我们现在改线上课了。每天作业打卡有时间要求的，所以咱们群里打卡，只能让其...   
19         徐乐遥                                            微信询问了孩子   
20         朱朗宁                                        考试结束了，还在上课，   
21         崔培烁                                                NaN   
22         官佳龙                                        阅读、作文这些比较欠缺   
23         许吉瑞                                              微信未接通   
24          滕瑜                                            微信询问了孩子   
25          严诺                                                NaN   
26         秦子墨                                         微信拒接，待会儿回复   
27         郭泽铭  早出晚归，一对一补习理科，数理化比较弱，英语是强项，语文一直在补习，还算不错，之前把作文交给...   
28         王纬恒                         孩子主要是阅读理解和写作方面比较薄弱，望老师多多指点   
29         王语涵  还有一个周期末考试，语文就是背的东西太多了，然后我就记得不扎实，古诗容易混，这个学而思的课都...   
30         于龙川  先谢谢您了他今年还有一对一的线下语文课，学而思的课算是他知识的拓展吧，因为上了两年了，也舍不...   
31         陈倩男  住校，学习基本自己负责，妈妈没怎么读书，不怎么管孩子学习，周五晚上六七点回家，语文中上，其他...   
32         刘晶凝                                    她阅读方便需要加强。丢分多一些   
33          胡业                                                NaN   
34         惠子鸣  他主要就是现代文阅读和作文这一块儿失分比较多，我也是一直很着急，不知道怎样才能更快的提分，妈...   
35         韩逸晴                                      还没期末考试，谢谢老师用心   
36         张超俊            昨天考的，还没出分，，选择题没问题，文言文对的改错了估计减2分，阅读可能减2分   
37         马心玥                                           和孩子聊得比较多   
38         谢韵雅                             好的，今天还要考最后一天，等她回来了我转告她   
39          马欢                                     老师，我们还没有期末考，好的   
40         蒋朝伟                           呦，看见的，可能是学校忙，还没有时间做，26考试   
41         王晨烨  从他上小学开始就培养他独立学习的习惯，跟他说不要依赖任何人，走上社会也是只能靠自己。所以从小...   
42         张梦雅                               把它打印出来 ，给小孩回来做，谢谢老师啦   
43     祝心悦 很优秀      秀珍老师，祝心悦考完期末试了，但是没有发成绩呢！今天才放假，所以打卡没有参加，不好意思啊！   
44          睿宇                                                已聊过   
45         张益铭                                            正在准备期末考   
46  孙鸣杰 寒假转出去了                           不过上了学而思之后，语文的确有进步了。谢谢老师！   
47         刘昱凡  昱凡在您这边的课一直是我在跟进，但最近我老父亲去世了，导致孩子最近的作业没有及时完成，我尽量...   
48         周立原                                     立原爸爸，立原期末考试了吗？   
49         张紫馨                                               周三考试   
50    徐子溪 爸爸妈妈                                       子溪妈妈，您现在有空吗？   
51    徐铜辰 沟通很少                                       铜辰妈妈，孩子回家了吗？   

                        Unnamed: 2  \
0                           1.25考试   
1                 115-120左右，作文52左右   
2                              NaN   
3                              NaN   
4                              NaN   
5                              NaN   
6                              NaN   
7                              NaN   
8           

In [3]:
data = pd.read_excel(r"C:\Users\Administrator\Desktop\寒假沟通记录表.xlsx",sheet_name=1,header=None)
data 

0    1    2
0    马欢  文佳聪  张梦雅
1   徐铜辰  韩逸晴  郭晓涵
2   韩逸晴  徐铜辰  马心玥
3   王嘉皓   马欢  文佳聪
4   宫肇轩  张梦雅  韩逸晴
5    于涵   李鹏  徐铜辰
6   陈雪利  陈雪利   马欢
7   于雯淼  宫肇轩  王嘉皓
8   赵启正  于雯淼   李鹏
9   崔培烁  王嘉皓  杜婧蕾
10  郭泽铭  杜婧蕾   于涵
11  许吉瑞   于涵  宋文浩
12   滕瑜  郝翊帆  赵启正
13  NaN  赵启正  陈雪利
14  NaN  郭泽铭  于雯淼
15  NaN  刘晶凝  宫肇轩
16  NaN  许吉瑞  郝翊帆
17  NaN   滕瑜  崔培烁
18  NaN  官佳龙  官佳龙
19  NaN  NaN  郭泽铭
20  NaN  NaN  许吉瑞
21  NaN  NaN  刘晶凝
22  NaN  NaN  孙雨涵
23  NaN  NaN   滕瑜

In [5]:
name = []
for i in data.loc[:,0]:
    for j in data.loc[:,1]:
        if i == j:
            for k in data.loc[:,2]:
                if j == k:
                    name.append(k)
name        

['马欢',
 '徐铜辰',
 '韩逸晴',
 '王嘉皓',
 '宫肇轩',
 '于涵',
 '陈雪利',
 '于雯淼',
 '赵启正',
 '郭泽铭',
 '许吉瑞',
 '滕瑜']

In [6]:
len(name)

12

In [1]:
import torch
a = torch.rand(4,32,8)
b = torch.rand(5,32,8)
c = torch.cat([a,b],dim = 0).shape

In [2]:
c

torch.Size([9, 32, 8])

In [3]:
a = torch.rand(32,8)
b = torch.rand(32,8)
torch.stack([a,b],dim = 0).shape

torch.Size([2, 32, 8])

In [6]:
c= torch.stack([a,b],dim = 0)
aa , bb = c.split([1,1],dim = 0)
print(aa.shape,bb.shape)

torch.Size([1, 32, 8]) torch.Size([1, 32, 8])


In [7]:
cc = torch.stack([a,a,b,b,a,a,b,b],dim = 0)
cc.shape

torch.Size([8, 32, 8])

In [9]:
aaa,bbb= cc.chunk(2,dim = 0)    # 做除法
print(aaa.shape,bbb.shape)

torch.Size([4, 32, 8]) torch.Size([4, 32, 8])


In [13]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(1, dtype=torch.uint8)

In [14]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(1, dtype=torch.uint8)

In [15]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(1, dtype=torch.uint8)

In [23]:
aaaa = torch.Tensor([[3.,3.],[3.,3.]])
bbbb = torch.ones(2,2)

In [24]:
print(aaaa,bbbb)

tensor([[3., 3.],
        [3., 3.]]) tensor([[1., 1.],
        [1., 1.]])


In [28]:
x = torch.mm(aaaa,bbbb)
y = torch.matmul(aaaa,bbbb)
z = aaaa@bbbb

In [32]:
x

tensor([[6., 6.],
        [6., 6.]])

In [33]:
y

tensor([[6., 6.],
        [6., 6.]])

In [34]:
z

tensor([[6., 6.],
        [6., 6.]])

In [35]:
s = torch.exp(torch.ones(2,2))
s

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [36]:
torch.log(s)

tensor([[1., 1.],
        [1., 1.]])

In [37]:
a = torch.tensor(3.14)
print(a.floor(),a.ceil(),a.trunc(),a.frac())

tensor(3.) tensor(4.) tensor(3.) tensor(0.1400)


In [38]:
e = torch.empty(5,5)
e

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [39]:
i = torch.rand_like(e,dtype = torch.float)
i

tensor([[0.9890, 0.2545, 0.3543, 0.6772, 0.9557],
        [0.4585, 0.8873, 0.5009, 0.2064, 0.6164],
        [0.6616, 0.7603, 0.4838, 0.8841, 0.0931],
        [0.3597, 0.4640, 0.5987, 0.5527, 0.4398],
        [0.3163, 0.6001, 0.1099, 0.5374, 0.0503]])

In [40]:
u = torch.tensor([[1,2,3],[4,5,6]])
u

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
u.resize(3,2)

E:\environment\lib\site-packages\torch\tensor.py:287: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [42]:
u.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [43]:
u.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [46]:
w = torch.tensor([22,45,1,13,23,89,65,3,8,53])
torch.sort(w)

(tensor([ 1,  3,  8, 13, 22, 23, 45, 53, 65, 89]),
 tensor([2, 7, 8, 3, 0, 4, 1, 9, 6, 5]))

In [49]:
torch.topk(w,k = 5,dim = 0,largest = True,out=None)

(tensor([89, 65, 53, 45, 23]), tensor([5, 6, 9, 1, 4]))

In [50]:
torch.kthvalue(w,5,dim = 0)   # 沿着指定维度返回第k个最小值及其索引

(tensor(22), tensor(0))

In [51]:
ww = torch.isnan(w)
ww

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [52]:
w.numpy()

array([22, 45,  1, 13, 23, 89, 65,  3,  8, 53], dtype=int64)

In [54]:
n = w.numpy()
nn = torch.from_numpy(n)
nn

tensor([22, 45,  1, 13, 23, 89, 65,  3,  8, 53])

In [55]:
torch.cuda

<module 'torch.cuda' from 'E:\\environment\\lib\\site-packages\\torch\\cuda\\__init__.py'>

In [56]:
torch.cuda.is_available()

False